project:
  name: morefocus-admin
  log-directory: /Users/jun/Desktop/temp/logs/

server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: '@profiles.active@'

swagger:
  host: localhost:${server.port}
  tag-class: cn.morefocus.admin.constants.AdminSwaggerTagConst

classified-protect:
  # 连续登录失败次数则锁定，-1表示不受限制，可以一直尝试登录
  login-max-fail-times: 5
  # 连续登录失败锁定时间（单位：秒），-1表示不锁定，建议锁定30分钟
  login-fail-locked-seconds: 1800
  # 密码复杂度开启（默认复杂度为：至少三种字符，最小 8 位）, true 开启，false 不开启，建议开启
  password-complexity-enabled: true

sa-token:
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800
  # token 有效期（单位：秒） 1天（86400秒），-1 代表永久有效
  timeout: 86400